"""empty message

Revision ID: cdf766501c01
Revises: 1b7c44194f2f
Create Date: 2019-04-30 16:30:20.786538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf766501c01'
down_revision = '1b7c44194f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_valid',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_valid')
    # ### end Alembic commands ###
